name: package_platform_detector
description: Flutter Package Platform Detector analyzes Flutter project dependencies.
homepage: https://github.com/onestudio-co/flutter-package-platform-detector
repository: https://github.com/onestudio-co/flutter-package-platform-detector

version: 0.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  yaml: ^3.1.2
  csv: ^5.0.2
  pub_updater: ^0.3.1
  interact: ^2.2.0
  args: ^2.4.2

executables:
  package_platform_detector:

