name: package_platform_detector
description: Flutter Package Platform Detector analyzes Flutter project dependencies.
homepage: https://github.com/onestudio-co/flutter-package-platform-detector
repository: https://github.com/onestudio-co/flutter-package-platform-detector

version: 0.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.5
  yaml: ^3.1.2
  csv: ^5.0.2
  pub_updater: ^0.2.2
  interact: ^2.2.0
  args: ^2.4.2

executables:
  package_platform_detector:

